server:
  port: 9020 #配置端口
  compression: #配置数据压缩
    enabled: true
    mime-types:
      - image/svg+xml
      - image/x-icon
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
      - font/x-font-woff
      - text/plain
    min-response-size: 2048
spring:
  servlet: #上传文件大小限制
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
    undertow: #undertow容器配置
      buffer-size: 512
      io-threads: 4
      worker-threads: 160
  datasource: #数据源
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/h2
    username:
    password:
    hikari: #连接池配置
      idle-timeout: 60000
      maximum-pool-size: 60
      minimum-idle: 10
  jpa: #jpa配置
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  mail: #邮件配置
    username:
    password:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
app: #系统参数配置
  verification-expired-minutes: 30
  star-limit: 30 #标记个数限制
  search-limit: 100 #搜索个数限制
  favorites-limit: 40 #显示收藏个数限制
  search-type-json: search.json #搜索类型数据
  init-capacity: 50 #初始容量(M)
  file-repository: ./repository #文件仓库
  file-compress-level: 7
  file-suffixes: txt,properties,yml,xml,sh,bat,sql,json
  recommends:
    - bilibili,https://www.bilibili.com/
    - 淘宝,https://www.taobao.com/
    - 知乎,https://www.zhihu.com/
    - 京东,https://www.jd.com/
    - 腾讯视频,https://v.qq.com/
    - 今日头条,https://www.toutiao.com/
jwt: #jwt令牌配置
  token-secret-key:
  token-expired-seconds: 7200