server:
  port: 9020 #端口
  compression:
    enabled: true #开启压缩功能
    mime-types:
      - image/svg+xml
      - image/x-icon
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json
      - font/x-font-woff
      - text/plain
    min-response-size: 2048
spring:
  servlet: #网关请求配置大小
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource: #数据源
    url: jdbc:h2:file:./db/h2
  jpa: #jpa配置
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  mail: #邮件配置
    username:
    password:
    host:
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
app:
  star-nums: 30 #标记个数限制
  search-nums: 100 #搜索个数限制
  favorites-nums: 40 #显示收藏个数限制
  data-url: search.json #搜索类型数据
  init-capacity: 50 #初始容量(M)
  file-repository: ./repository #文件仓库
  recommends:
    - bilibili,https://www.bilibili.com/
    - 淘宝,https://www.taobao.com/
    - 知乎,https://www.zhihu.com/
    - 京东,https://www.jd.com/
    - 腾讯视频,https://v.qq.com/
    - 今日头条,https://www.toutiao.com/