netty:
  port: 8888 #netty端口
server:
  port: 9020 #应用端口
  compression: #开启数据压缩
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  servlet:
    multipart: #上传文件大小限制
      location: ${java.io.tmpdir}
      max-file-size: 512MB
      max-request-size: 512MB
    undertow: #undertow容器配置
      buffer-size: 512
      io-threads: 4
      worker-threads: 160
  datasource: #数据源
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/h2
    username:
    password:
    hikari: #连接池配置
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 300000
      maximum-pool-size: 100
      minimum-idle: 10
      pool-name: myHikariCP
  jpa: #jpa配置
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2: #h2数据库配置
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  mail: #邮件配置
    username:
    password:
    host: smtp.qq.com
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
app: #系统参数配置
  error-count-limit: 5000 #登录错误次数限制
  recycle-save-days: 30 #回收站保存时间
  verification-expired-minutes: 30 #验证码过期时间
  verification-resend-seconds: 60 #验证码重发时间
  star-limit: 40 #标记个数限制
  navigation-limit: 6 #快捷导航个数限制
  favorites-search-limit: 100 #搜索收藏个数限制
  category-search-limit: 30 #搜索分类个数限制
  favorites-limit: 40 #显示收藏个数限制
  init-capacity: 100 #初始容量(M)
  file-repository: ./repository #文件仓库
  file-deep-level: 10 #文件夹深度
  file-compress-level: 7 #文件压缩等级
  file-suffixes: txt,properties,yml,xml,sh,bat,sql,json #可查看文件
jwt: #jwt令牌配置
  token-secret-key:
  token-expired-seconds: 7200
cron: #定时任务
  task-notice-job: '0 0,30 8-20 * * ?'
  recycle-job: '0 1 0 * * ?'
  data-clean-job: '0 2 0 * * ?'
  backup-job: '0 3 0 * * ?'
backup: #数据库备份文件地址
  zip-file-path: ./backup/h2.zip
aes: #aes密钥
  secret-key:
swagger:
  enable: false #开启swagger